--
-- PostgreSQL database dump
--

-- Dumped from database version 13.5 (Debian 13.5-1.pgdg110+1)
-- Dumped by pg_dump version 13.5 (Ubuntu 13.5-0ubuntu0.21.10.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: customers; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.customers (
    user_id bigint NOT NULL,
    address character varying(255)
);


ALTER TABLE public.customers OWNER TO postgres;

--
-- Name: databasechangelog; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.databasechangelog (
    id character varying(255) NOT NULL,
    author character varying(255) NOT NULL,
    filename character varying(255) NOT NULL,
    dateexecuted timestamp without time zone NOT NULL,
    orderexecuted integer NOT NULL,
    exectype character varying(10) NOT NULL,
    md5sum character varying(35),
    description character varying(255),
    comments character varying(255),
    tag character varying(255),
    liquibase character varying(20),
    contexts character varying(255),
    labels character varying(255),
    deployment_id character varying(10)
);


ALTER TABLE public.databasechangelog OWNER TO postgres;

--
-- Name: databasechangeloglock; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.databasechangeloglock (
    id integer NOT NULL,
    locked boolean NOT NULL,
    lockgranted timestamp without time zone,
    lockedby character varying(255)
);


ALTER TABLE public.databasechangeloglock OWNER TO postgres;

--
-- Name: discounts; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.discounts (
    discount_id bigint NOT NULL,
    percentage integer NOT NULL,
    start_date date NOT NULL,
    end_date date NOT NULL,
    description character varying(255),
    salesman_id bigint NOT NULL
);


ALTER TABLE public.discounts OWNER TO postgres;

--
-- Name: hibernate_sequence; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.hibernate_sequence
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.hibernate_sequence OWNER TO postgres;

--
-- Name: order_item; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.order_item (
    order_item_id integer NOT NULL,
    quantity integer NOT NULL,
    order_id bigint NOT NULL,
    product_id bigint NOT NULL
);


ALTER TABLE public.order_item OWNER TO postgres;

--
-- Name: order_item_order_item_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.order_item ALTER COLUMN order_item_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.order_item_order_item_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: orders; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.orders (
    order_id bigint NOT NULL,
    time_of_order timestamp without time zone NOT NULL,
    is_delivered boolean NOT NULL,
    grade integer NOT NULL,
    comment character varying(255),
    is_anon_comment boolean,
    is_archived_comment boolean,
    user_id bigint NOT NULL,
    salesman_id bigint NOT NULL
);


ALTER TABLE public.orders OWNER TO postgres;

--
-- Name: products; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.products (
    product_id bigint NOT NULL,
    product_name character varying(255) NOT NULL,
    product_price double precision NOT NULL,
    product_description character varying(255) NOT NULL,
    product_image character varying(255) NOT NULL,
    salesman_id bigint NOT NULL
);


ALTER TABLE public.products OWNER TO postgres;

--
-- Name: salesman; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.salesman (
    user_id bigint NOT NULL,
    registration_date date NOT NULL,
    email character varying(255) NOT NULL,
    address character varying(255) NOT NULL,
    company_name character varying(255) NOT NULL
);


ALTER TABLE public.salesman OWNER TO postgres;

--
-- Name: user_role_list; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.user_role_list (
    user_user_id bigint NOT NULL,
    role_list integer
);


ALTER TABLE public.user_role_list OWNER TO postgres;

--
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    user_id bigint NOT NULL,
    first_name character varying(255) NOT NULL,
    surname character varying(255) NOT NULL,
    username character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    active boolean NOT NULL
);


ALTER TABLE public.users OWNER TO postgres;

--
-- Data for Name: customers; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.customers (user_id, address) FROM stdin;
2	SomeAddress
\.


--
-- Data for Name: databasechangelog; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.databasechangelog (id, author, filename, dateexecuted, orderexecuted, exectype, md5sum, description, comments, tag, liquibase, contexts, labels, deployment_id) FROM stdin;
1641724801093-1	ivke (generated)	db/changelog/2022/01/09-01-changelog.xml	2022-01-09 12:52:08.246	1	EXECUTED	8:66d339bfb0b07ca6736080b2bc5a37fd	createSequence sequenceName=hibernate_sequence		\N	3.10.3	\N	\N	1729128184
1641724801093-2	ivke (generated)	db/changelog/2022/01/09-01-changelog.xml	2022-01-09 12:52:08.251474	2	EXECUTED	8:998087f3ca9f655d46101a3fa7a62224	createTable tableName=customers		\N	3.10.3	\N	\N	1729128184
1641724801093-3	ivke (generated)	db/changelog/2022/01/09-01-changelog.xml	2022-01-09 12:52:08.256117	3	EXECUTED	8:1ce15e38028bf4a00a1780072c9407a0	createTable tableName=discounts		\N	3.10.3	\N	\N	1729128184
1641724801093-4	ivke (generated)	db/changelog/2022/01/09-01-changelog.xml	2022-01-09 12:52:08.260718	4	EXECUTED	8:4714950ab70bd1483f7ff8bfd20ceb68	createTable tableName=order_item		\N	3.10.3	\N	\N	1729128184
1641724801093-5	ivke (generated)	db/changelog/2022/01/09-01-changelog.xml	2022-01-09 12:52:08.265252	5	EXECUTED	8:f97ec11d5cd7ab1d1b5129c37d2448cb	createTable tableName=orders		\N	3.10.3	\N	\N	1729128184
1641724801093-6	ivke (generated)	db/changelog/2022/01/09-01-changelog.xml	2022-01-09 12:52:08.271282	6	EXECUTED	8:7fb061701466ae10ea22ea84c9dac0c4	createTable tableName=products		\N	3.10.3	\N	\N	1729128184
1641724801093-7	ivke (generated)	db/changelog/2022/01/09-01-changelog.xml	2022-01-09 12:52:08.276983	7	EXECUTED	8:a498b0bdc10796b9801b31b22ac8d6fc	createTable tableName=salesman		\N	3.10.3	\N	\N	1729128184
1641724801093-8	ivke (generated)	db/changelog/2022/01/09-01-changelog.xml	2022-01-09 12:52:08.279613	8	EXECUTED	8:a34478ba4be86972d19b0f0ede9f0e3d	createTable tableName=user_role_list		\N	3.10.3	\N	\N	1729128184
1641724801093-9	ivke (generated)	db/changelog/2022/01/09-01-changelog.xml	2022-01-09 12:52:08.285901	9	EXECUTED	8:e34763295a143746f7b5db6f854bac26	createTable tableName=users		\N	3.10.3	\N	\N	1729128184
1641724801093-10	ivke (generated)	db/changelog/2022/01/09-01-changelog.xml	2022-01-09 12:52:08.28994	10	EXECUTED	8:dfb3b615091f684c63aea2a3c0278aab	addUniqueConstraint constraintName=uc_discounts_discount, tableName=discounts		\N	3.10.3	\N	\N	1729128184
1641724801093-11	ivke (generated)	db/changelog/2022/01/09-01-changelog.xml	2022-01-09 12:52:08.293993	11	EXECUTED	8:2a6c0784c0fd3629abbe16e4cc03ed2b	addUniqueConstraint constraintName=uc_order_item_order_item, tableName=order_item		\N	3.10.3	\N	\N	1729128184
1641724801093-12	ivke (generated)	db/changelog/2022/01/09-01-changelog.xml	2022-01-09 12:52:08.297909	12	EXECUTED	8:015a991ef10327ec41d528f1fed48efe	addUniqueConstraint constraintName=uc_orders_order, tableName=orders		\N	3.10.3	\N	\N	1729128184
1641724801093-13	ivke (generated)	db/changelog/2022/01/09-01-changelog.xml	2022-01-09 12:52:08.301522	13	EXECUTED	8:b707801b4b72cbdca6db2171bf8a563e	addUniqueConstraint constraintName=uc_products_product, tableName=products		\N	3.10.3	\N	\N	1729128184
1641724801093-14	ivke (generated)	db/changelog/2022/01/09-01-changelog.xml	2022-01-09 12:52:08.305497	14	EXECUTED	8:d330e08c71488fa6ef69de18dacd8ada	addUniqueConstraint constraintName=uc_user_role_list_user_user, tableName=user_role_list		\N	3.10.3	\N	\N	1729128184
1641724801093-15	ivke (generated)	db/changelog/2022/01/09-01-changelog.xml	2022-01-09 12:52:08.309296	15	EXECUTED	8:d78d6940e13bd980ff993cd885c51fb5	addUniqueConstraint constraintName=uc_users_user, tableName=users		\N	3.10.3	\N	\N	1729128184
1641724801093-16	ivke (generated)	db/changelog/2022/01/09-01-changelog.xml	2022-01-09 12:52:08.313455	16	EXECUTED	8:f5ef5ab2f1fbc73770703c5717a4237f	addUniqueConstraint constraintName=uc_users_username, tableName=users		\N	3.10.3	\N	\N	1729128184
1641724801093-17	ivke (generated)	db/changelog/2022/01/09-01-changelog.xml	2022-01-09 12:52:08.316724	17	EXECUTED	8:3ef2e092986c834fa01b4c38a5ffbe3e	addForeignKeyConstraint baseTableName=customers, constraintName=FK_CUSTOMERS_ON_USER, referencedTableName=users		\N	3.10.3	\N	\N	1729128184
1641724801093-18	ivke (generated)	db/changelog/2022/01/09-01-changelog.xml	2022-01-09 12:52:08.319189	18	EXECUTED	8:fb65e9cc7aaefddb39f012e4243e21c9	addForeignKeyConstraint baseTableName=discounts, constraintName=FK_DISCOUNTS_ON_SALESMAN, referencedTableName=salesman		\N	3.10.3	\N	\N	1729128184
1641724801093-19	ivke (generated)	db/changelog/2022/01/09-01-changelog.xml	2022-01-09 12:52:08.321645	19	EXECUTED	8:90f1df609f20d2a02cdb0b931582a5b2	addForeignKeyConstraint baseTableName=orders, constraintName=FK_ORDERS_ON_SALESMAN, referencedTableName=salesman		\N	3.10.3	\N	\N	1729128184
1641724801093-20	ivke (generated)	db/changelog/2022/01/09-01-changelog.xml	2022-01-09 12:52:08.323991	20	EXECUTED	8:79b66d2c5edfb23d23b1015ca833e904	addForeignKeyConstraint baseTableName=orders, constraintName=FK_ORDERS_ON_USER, referencedTableName=customers		\N	3.10.3	\N	\N	1729128184
1641724801093-21	ivke (generated)	db/changelog/2022/01/09-01-changelog.xml	2022-01-09 12:52:08.326553	21	EXECUTED	8:b5be9804b5624f2f8b629bb9e4712698	addForeignKeyConstraint baseTableName=order_item, constraintName=FK_ORDER_ITEM_ON_ORDER, referencedTableName=orders		\N	3.10.3	\N	\N	1729128184
1641724801093-22	ivke (generated)	db/changelog/2022/01/09-01-changelog.xml	2022-01-09 12:52:08.328992	22	EXECUTED	8:86b0d3b2c41146837b37d015c2f6863a	addForeignKeyConstraint baseTableName=order_item, constraintName=FK_ORDER_ITEM_ON_PRODUCT, referencedTableName=products		\N	3.10.3	\N	\N	1729128184
1641724801093-23	ivke (generated)	db/changelog/2022/01/09-01-changelog.xml	2022-01-09 12:52:08.331606	23	EXECUTED	8:babf491d4d060a2dcf5726dee5aed566	addForeignKeyConstraint baseTableName=products, constraintName=FK_PRODUCTS_ON_SALESMAN, referencedTableName=salesman		\N	3.10.3	\N	\N	1729128184
1641724801093-24	ivke (generated)	db/changelog/2022/01/09-01-changelog.xml	2022-01-09 12:52:08.334065	24	EXECUTED	8:8aff52ca77e731b50ecd2102efdd5f57	addForeignKeyConstraint baseTableName=salesman, constraintName=FK_SALESMAN_ON_USER, referencedTableName=users		\N	3.10.3	\N	\N	1729128184
1641724801093-25	ivke (generated)	db/changelog/2022/01/09-01-changelog.xml	2022-01-09 12:52:08.33659	25	EXECUTED	8:915fb8dec02537ad6a34290aacf43213	addForeignKeyConstraint baseTableName=user_role_list, constraintName=fk_user_rolelist_on_user, referencedTableName=users		\N	3.10.3	\N	\N	1729128184
\.


--
-- Data for Name: databasechangeloglock; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.databasechangeloglock (id, locked, lockgranted, lockedby) FROM stdin;
1	f	\N	\N
\.


--
-- Data for Name: discounts; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.discounts (discount_id, percentage, start_date, end_date, description, salesman_id) FROM stdin;
\.


--
-- Data for Name: order_item; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.order_item (order_item_id, quantity, order_id, product_id) FROM stdin;
\.


--
-- Data for Name: orders; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.orders (order_id, time_of_order, is_delivered, grade, comment, is_anon_comment, is_archived_comment, user_id, salesman_id) FROM stdin;
4	2022-01-09 12:52:10.195578	t	4	It was beautiful doing business with this firm	f	f	2	3
5	2022-01-09 12:52:10.195648	t	4	Lorem Ipsum је једноставно модел текста који се користи у штампарској и словослагачкој индустрији.	t	f	2	3
6	2022-01-09 12:52:10.195659	t	4	Ovaj tekst napisan na latinskom jeziku, ili bar njegove dve početne reči poznate su štamparima...	t	f	2	3
7	2022-01-09 12:52:10.195667	t	4	Umesto da koristi tekst koji, na primer, glasi “Proba, proba, proba…” ili “Ovo je mesto za tekst, ovo..	t	f	2	3
8	2022-01-09 12:52:10.195675	t	3	То значи да овде генерисани Lorem Ipsum не садржи понављање, нема убачен хумор или неке неочекиване речи и тако даље	f	f	2	3
9	2022-01-09 12:52:10.195683	t	5	Moram vam objasniti kako je rođena čitava ova pogrešna ideja kojom se osuđuje zadovoljstvo i veliča bol...	f	f	2	3
\.


--
-- Data for Name: products; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.products (product_id, product_name, product_price, product_description, product_image, salesman_id) FROM stdin;
\.


--
-- Data for Name: salesman; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.salesman (user_id, registration_date, email, address, company_name) FROM stdin;
3	2022-01-09	email@email.com	Adresa 231	Neka kompanija
\.


--
-- Data for Name: user_role_list; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.user_role_list (user_user_id, role_list) FROM stdin;
1	0
2	1
3	2
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users (user_id, first_name, surname, username, password, active) FROM stdin;
1	Zelena	Buric	zelena	123456	t
2	Boris	Gunovic	boris123	{bcrypt}$2a$10$3n.7D/1QhFKg0LW5tjy5sOw5cEMGsnZ/OfjMpwklTWacCJ0wBlSaa	t
3	Ivan	Djuraki	ivke	123456	t
\.


--
-- Name: hibernate_sequence; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.hibernate_sequence', 9, true);


--
-- Name: order_item_order_item_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.order_item_order_item_id_seq', 1, false);


--
-- Name: databasechangeloglock databasechangeloglock_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.databasechangeloglock
    ADD CONSTRAINT databasechangeloglock_pkey PRIMARY KEY (id);


--
-- Name: customers pk_customers; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.customers
    ADD CONSTRAINT pk_customers PRIMARY KEY (user_id);


--
-- Name: discounts pk_discounts; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.discounts
    ADD CONSTRAINT pk_discounts PRIMARY KEY (discount_id);


--
-- Name: order_item pk_order_item; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.order_item
    ADD CONSTRAINT pk_order_item PRIMARY KEY (order_item_id);


--
-- Name: orders pk_orders; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT pk_orders PRIMARY KEY (order_id);


--
-- Name: products pk_products; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT pk_products PRIMARY KEY (product_id);


--
-- Name: salesman pk_salesman; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.salesman
    ADD CONSTRAINT pk_salesman PRIMARY KEY (user_id);


--
-- Name: users pk_users; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT pk_users PRIMARY KEY (user_id);


--
-- Name: discounts uc_discounts_discount; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.discounts
    ADD CONSTRAINT uc_discounts_discount UNIQUE (discount_id);


--
-- Name: order_item uc_order_item_order_item; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.order_item
    ADD CONSTRAINT uc_order_item_order_item UNIQUE (order_item_id);


--
-- Name: orders uc_orders_order; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT uc_orders_order UNIQUE (order_id);


--
-- Name: products uc_products_product; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT uc_products_product UNIQUE (product_id);


--
-- Name: user_role_list uc_user_role_list_user_user; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_role_list
    ADD CONSTRAINT uc_user_role_list_user_user UNIQUE (user_user_id);


--
-- Name: users uc_users_user; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uc_users_user UNIQUE (user_id);


--
-- Name: users uc_users_username; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uc_users_username UNIQUE (username);


--
-- Name: customers fk_customers_on_user; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.customers
    ADD CONSTRAINT fk_customers_on_user FOREIGN KEY (user_id) REFERENCES public.users(user_id);


--
-- Name: discounts fk_discounts_on_salesman; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.discounts
    ADD CONSTRAINT fk_discounts_on_salesman FOREIGN KEY (salesman_id) REFERENCES public.salesman(user_id);


--
-- Name: order_item fk_order_item_on_order; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.order_item
    ADD CONSTRAINT fk_order_item_on_order FOREIGN KEY (order_id) REFERENCES public.orders(order_id);


--
-- Name: order_item fk_order_item_on_product; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.order_item
    ADD CONSTRAINT fk_order_item_on_product FOREIGN KEY (product_id) REFERENCES public.products(product_id);


--
-- Name: orders fk_orders_on_salesman; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT fk_orders_on_salesman FOREIGN KEY (salesman_id) REFERENCES public.salesman(user_id);


--
-- Name: orders fk_orders_on_user; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT fk_orders_on_user FOREIGN KEY (user_id) REFERENCES public.customers(user_id);


--
-- Name: products fk_products_on_salesman; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT fk_products_on_salesman FOREIGN KEY (salesman_id) REFERENCES public.salesman(user_id);


--
-- Name: salesman fk_salesman_on_user; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.salesman
    ADD CONSTRAINT fk_salesman_on_user FOREIGN KEY (user_id) REFERENCES public.users(user_id);


--
-- Name: user_role_list fk_user_rolelist_on_user; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_role_list
    ADD CONSTRAINT fk_user_rolelist_on_user FOREIGN KEY (user_user_id) REFERENCES public.users(user_id);


--
-- PostgreSQL database dump complete
--

