version: '2.2'
services:
  database_ues:
    image: postgres:14.1
    container_name: database
    volumes:
      - database_ues:/var/lib/postgresql/data
    ports:
      - "5445:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    mem_limit: 1000m
    mem_reservation: 300m
  es01_ues:
    image: elasticsearch-sr:latest 
    container_name: es01_ues
    environment:
      - node.name=es01_ues
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es02_ues,es03_ues
      - cluster.initial_master_nodes=es01_ues,es02_ues,es03_ues
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1000m
    volumes:
      - data01_ues:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - elastic
  es02_ues:
    image: elasticsearch-sr:latest
    container_name: es02_ues
    environment:
      - node.name=es02_ues
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01_ues,es03_ues
      - cluster.initial_master_nodes=es01_ues,es02_ues,es03_ues
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1000m
    volumes:
      - data02_ues:/usr/share/elasticsearch/data
    networks:
      - elastic
  es03_ues:
    image: elasticsearch-sr:latest
    container_name: es03_ues
    environment:
      - node.name=es03_ues
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01_ues,es02_ues
      - cluster.initial_master_nodes=es01_ues,es02_ues,es03_ues
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1000m
    volumes:
      - data03_ues:/usr/share/elasticsearch/data
    networks:
      - elastic

volumes:
  data01_ues:
    driver: local
  data02_ues:
    driver: local
  data03_ues:
    driver: local
  database_ues:

networks:
  elastic:
    driver: bridge

