FROM gradle:7-jdk16 as cache
RUN mkdir -p /home/gradle/cache_home
ENV GRADLE_USER_HOME /home/gradle/cache_home
COPY build.gradle.kts /home/gradle/code/
COPY gradle.properties /home/gradle/cache_home
WORKDIR /home/gradle/code
RUN gradle clean build -i --stacktrace -x bootJar


FROM bellsoft/liberica-openjdk-alpine-musl:16 as builder
COPY --from=cache /home/gradle/cache_home /home/gradle/.gradle
COPY . /app
WORKDIR /app
RUN ./gradlew bootJar --stacktrace
ADD build/libs/*-?.?.?.jar application.jar
RUN java -Djarmode=layertools -jar application.jar extract


FROM bellsoft/liberica-openjdk-alpine-musl:16
WORKDIR /app
COPY --from=builder /app/dependencies/ ./
COPY --from=builder /app/snapshot-dependencies/ ./
COPY --from=builder /app/spring-boot-loader/ ./
COPY --from=builder /app/application/ ./
EXPOSE 8080
ENTRYPOINT ["java"]
CMD ["org.springframework.boot.loader.JarLauncher"]

